from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from datetime import date
from enum import Enum


class TrialPhase(str, Enum):
    PHASE1 = "Phase 1"
    PHASE2 = "Phase 2"
    PHASE3 = "Phase 3"
    PHASE4 = "Phase 4"
    NA = "N/A"


class TrialStatus(str, Enum):
    RECRUITING = "Recruiting"
    ACTIVE_NOT_RECRUITING = "Active, not recruiting"
    ENROLLING_BY_INVITATION = "Enrolling by invitation"
    COMPLETED = "Completed"


class TrialSite(BaseModel):
    facility: str
    city: str
    state: str
    country: str
    zip_code: str
    lat: Optional[float] = None
    lng: Optional[float] = None


class Trial(BaseModel):
    """Represents a clinical trial used for patient matching."""

    trial_id: str = Field(
        ...,
        description="ClinicalTrials.gov identifier in NCT format.",
        json_schema_extra={"example": "NCT04521234"},
    )

    # Support both field names: 'title' (API/ingest) and 'official_title' (seed data)
    title: Optional[str] = Field(
        default=None,
        description="Full official title of the clinical trial.",
        json_schema_extra={"example": "A Study of Semaglutide in Type 2 Diabetes"},
    )
    official_title: Optional[str] = Field(
        default=None,
        description="Full official title (used by seed data).",
    )

    # Summary / description
    brief_summary: str = Field(
        default="",
        description="Brief summary of the trial.",
    )

    phase: str = Field(
        default="N/A",
        description="Trial phase (e.g. 'Phase 1', 'Phase 2', 'Phase 3', 'Phase 4', 'N/A').",
        json_schema_extra={"example": "Phase 2"},
    )
    status: Optional[str] = Field(
        default=None,
        description="Current recruitment status.",
    )
    sponsor: str = Field(
        default="Unknown",
        description="Name of the primary sponsor organisation.",
        json_schema_extra={"example": "Novo Nordisk A/S"},
    )

    # Dates – accept both str and date object for flexibility
    start_date: Optional[str] = Field(
        default=None,
        description="Trial start date.",
        json_schema_extra={"example": "2024-03-01"},
    )
    end_date: Optional[str] = Field(
        default=None,
        description="Estimated or actual trial end date.",
        json_schema_extra={"example": "2026-09-30"},
    )

    location: str = Field(
        default="Unknown",
        description="Primary site or city/country where the trial is conducted.",
        json_schema_extra={"example": "Stanford Medical Center, Palo Alto, CA, USA"},
    )

    # Trial sites list (from seed data)
    sites: List[TrialSite] = Field(default_factory=list)

    # ── NLP Integration ─────────────────────────────────────────────────────────
    # The structured logic tree generated by parser.py
    criteria_json: Dict[str, Any] = Field(default_factory=dict)

    # Raw criteria text — used both for API ingestion and LLM fallback
    criteria_text: str = Field(
        default="",
        description=(
            "Raw eligibility criteria text as published on ClinicalTrials.gov, "
            "covering both inclusion and exclusion criteria."
        ),
        json_schema_extra={
            "example": (
                "Inclusion Criteria:\n"
                "  - Age 30–75 years\n"
                "  - Diagnosed with Type 2 Diabetes Mellitus (ICD-10: E11.9)\n\n"
                "Exclusion Criteria:\n"
                "  - Prior use of GLP-1 receptor agonists within 90 days"
            )
        },
    )
    raw_inclusion_criteria: str = ""
    raw_exclusion_criteria: str = ""

    # ── Geographic & Ethics Metadata ────────────────────────────────────────────
    is_remote: bool = False
    is_hpsa_zone: bool = False  # Health Professional Shortage Area bonus

    # __ Dropout Predictor Metrics ______________________________________________
    visits_required: int = 10
    telehealth_enabled: bool = False

    # __ Safety: Investigational Drug (for Polypharmacy Check) __________________
    investigational_drug: str = ""

    # Extra fields used by seed data
    min_age: Optional[int] = None
    max_age: Optional[int] = None
    required_diagnoses: List[str] = Field(default_factory=list)

    @property
    def full_criteria_text(self) -> str:
        """Helper property for M3's Semantic Soft Matcher."""
        if self.criteria_text:
            return self.criteria_text
        raw_text = self.criteria_json.get("raw_text", {})
        if raw_text:
            return f"{raw_text.get('inclusion', '')} {raw_text.get('exclusion', '')}"
        return f"{self.raw_inclusion_criteria} {self.raw_exclusion_criteria}"

    model_config = {
        "json_schema_extra": {
            "example": {
                "trial_id": "NCT04521234",
                "title": "A Study of Semaglutide in Adults With Type 2 Diabetes",
                "phase": "Phase 2",
                "sponsor": "Novo Nordisk A/S",
                "location": "Stanford Medical Center, Palo Alto, CA, USA",
                "start_date": "2024-03-01",
                "end_date": "2026-09-30",
                "criteria_text": (
                    "Inclusion Criteria:\n"
                    "  - Age 30–75 years\n"
                    "  - Diagnosed with Type 2 Diabetes Mellitus (ICD-10: E11.9)\n"
                ),
            }
        }
    }
