from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from datetime import date
from enum import Enum

class TrialPhase(str, Enum):
    PHASE1 = "Phase 1"
    PHASE2 = "Phase 2"
    PHASE3 = "Phase 3"
    PHASE4 = "Phase 4"
    NA = "N/A"

class TrialStatus(str, Enum):
    RECRUITING = "Recruiting"
    ACTIVE_NOT_RECRUITING = "Active, not recruiting"
    ENROLLING_BY_INVITATION = "Enrolling by invitation"
    COMPLETED = "Completed"

class TrialSite(BaseModel):
    facility: str
    city: str
    state: str
    country: str
    zip_code: str
    lat: Optional[float] = None
    lng: Optional[float] = None

class Trial(BaseModel):
    trial_id: str
    official_title: str
    brief_summary: str = ""
    phase: TrialPhase
    status: TrialStatus
    sponsor: str
    start_date: Optional[date] = None
    sites: List[TrialSite] = []
    
    # --- M2 NLP Integration ---
    # The structured logic tree generated by parser.py
    criteria_json: Dict[str, Any] = Field(default_factory=dict)
    
    # Keep the raw text for the LLM fallback / Semantic Scoring
    raw_inclusion_criteria: str = ""
    raw_exclusion_criteria: str = ""
    
    # --- M3/M4 Geographic & Ethics Metadata ---
    location: str = "Unknown"
    is_remote: bool = False
    is_hpsa_zone: bool = False # Safeguard #1: Health Professional Shortage Area bonus
    
    # --- Dropout Predictor Metrics ---
    visits_required: int = 10
    telehealth_enabled: bool = False
    
    # --- Safety: Investigational Drug (for Polypharmacy Check) ---
    investigational_drug: str = ""

    @property
    def full_criteria_text(self) -> str:
        """Helper property for M3's Semantic Soft Matcher."""
        raw_text = self.criteria_json.get("raw_text", {})
        if raw_text:
            return f"{raw_text.get('inclusion', '')} {raw_text.get('exclusion', '')}"
        return f"{self.raw_inclusion_criteria} {self.raw_exclusion_criteria}"